version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - app-network

  api:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - api-solid-pg
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://docker:docker@api-solid-pg:5432/apisolid?schema=public
      - JWT_SECRET=fastifysolidapi
      - PORT=3333
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
